---
title: "Project Tips and Presentation Times"
output: 
  tufte::tufte_html:
    highlight: pygments
  #  css: "sta199-labs.css"
link-citations: yes
---

```{r include=FALSE}
library(tidyverse)
library(tufte)
library(knitr)
options(
  htmltools.dir.version = FALSE, # for blogdown
  show.signif.stars = FALSE,     # for regression output
  digits = 2
  )
```

# Finalizing your report!

You're in the homestretch! Your report guidelines are posted at the [website](https://sta-198-glhlth-298-fall-2022.github.io/website/). Note projects are due at 4pm Friday, November 18, with presentations 11/28, 11/30, or 12/5 (check Announcements on the website).


# Reviewing the draft

Carefully read the project draft, considering the questions below as you read it. 

## Introduction + Data

- Are the research question and goal of the report clearly stated? 
- Does the introduction provide appropriate background context and motivation for a general reader?
- Is the source of the data stated with an appropriate citation? 
- Is it clear when and how the data were originally collected?
- Are the observations and relevant variables described?

## Exploratory data analysis 

- Are the data cleaning and data wrangling clearly described? This includes dealing with missing data, creating new variables, etc.
- Do the visualizations follow the guidelines we've discussed in STA 198? This includes using plots that are appropriate for the data, having proper axis labels, titles, etc.
- Are any tables and figures clear, effective, and informative?  Should any be eliminated, or are any new tables or figures needed?
- Is the choice of statistical method justified?

## Methodology + Results

- Are the chosen methods (e.g. hypothesis testing, confidence intervals, models, etc.) for answering the research question appropriate for the research context and type of data?
- Is the research question answered accurately and effectively? 
- Is the answer to the research question summarized and supported by statistical arguments?
- Are limitations of the analysis clearly outlined?

## Writing + Reproducibility

- Is the paper professionally presented and generally free of distracting errors or other issues, including (but not limited to) insufficient organization or formatting; poor grammar, spelling, or punctuation; or too-small font? Is the overall paper easily readable for someone with your expert level of knowledge? 
- Knit the .Rmd file. Are you able to reproduce all aspects of the report, including output, 
visualizations, etc? This includes (1) being able to knit the document and (2) obtaining the same PDF as the original PDF. 

# Presentation Tips

The presentation is your time to show others your cool findings!  Be very careful not to exceed the 5 minute time limit -- be professional, and don't cut into the time of other teams. The most effective presentations will focus on research questions, data, and findings from the analysis -- smaller details can be left to the written report. While support from the data should be provided for conclusions, this should stay "big picture" and not get too far in the weeds (e.g., we don't need to know the name of every variable you considered, or how you had to use pivot table, in the presentation itself). Think about your audience as a group of health leaders and policy makers -- you want to make your point effectively, providing evidence your data support your points. 

# Presentation Day and Time

Note: you are expected to be present for *all* presentations unless you are ill. I plan to get ideas for exam questions from the project presentations, so don't miss them.

### Monday, November 28:

Hannah, Will, Vinith, and Raphael

Kayla, Grace, and Hailey

Abby, Anna C., and Laura

Dom, Kate, Dylan, and Albert

Kristen, Catherine, Montana, and Aditya

 

### Wednesday, November 30:

Carla, Juliet, Laura, and Noah

Rachel, Chiara, Fanbin, and Ariana

Laurel, Maya, Mare, and Gareth

Maura, Sarah, Deven, and Charlie

Zhenkun, Anna G., Michelle, and Erika

 

### Monday, December 5:

Akshay, Chichi, Claire, and Jasmine

Caroline, Hillary, and Melat

Alayna, Hanzhi, Karly, and Junpeng

Breanna, Brianna, and Habiba

